---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_GRAFANA_PASSWORD: AgAyxE57e03GHUWby92xo4HCk+T/FZaUqqHaAZCAqqp/ypkyTLgSsxkpg6JEvhV7Tsu8UHWfXVtRvgE2d8RXBW/he8jQ3tKcGsNRnmghqqnhO1hfZO8H4+mMoaFd3orgPWj772z/gboN33zwbQDlKWB6hplBLHCC+h8y1KUgeAnzCq/eK2JtL7PKPA3GEq+w2MZjD79yRur9k4htXsc/oFSuulIHnPvtk2D6JMZnDWc0ljOFrhTjUg2tr3lbY/xxcy6xutLKGTYU/sp+qZKSU4sZ35H27vvRzXX1EIiznnGfj+1MSsXMRXUPmdDC3Q+sq3xFqXDEaolX7SflreCHTbVS2ohf/eMtwgqYl+hJIwrvJ4YHtggZuulEuESMRoeY8BV2mcV59By8pau2YYX0RA2qdGVF0mrS9HXi+veflvmT3EpKcM4sWQjf03osXmKb+RBGp0vZkGXEazQxy71/Jzd4DAsfQQNsUDV6ZQc22XFoZiBo6rJDlROQBOPvecI1/JZvA5PzB34WsM9/hC1cdDjrZwttg4t0SvXTbZnrVBDhqPD1TyePxl2baYSVuQ+jNZmQZ2nvxWDkqd5SazM8ZKMqojkfa3rD/RWnCNjMP8j5OVhQImJqAYBiXYfEHny3qb7vW0cpftbY+N8zHXqr2b8wn/umO8pfAhzg3PiwvL+WwfqUKpU4tTtljq6BO6Y2aONoaaj+jWbRMiXKXk5oHeP1sTEzMQ==
  template:
    metadata:
      name: homepage-secrets
      namespace: homepage
