---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-homeassistant-token
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_HOMEASSISTANT_TOKEN: AgCCr33Buco4WUJzkOBCOFAs3vUwgCNBIpZwmXSf1xQMdxTK2y72eOBBz9LAw3SwTNMON1aDwUb/K2m/ktnJWEaQGhz20fX6a9rd2ZLzFwPBOnRP9BglFYVkqaruggCFGBuREIsOjyL51uqrBmQzjaJ5vA0w5EpqS+/1+tAo7wxf07+m1lacYHmqW8sWj4JXcvYpbngByNDbtOoXOba3PCn41nOc+CGUby45eomF6X7VmyPGxIZeSyuUCLZLaqm2l9zqCJUCQT2oQJClijBzRSqUvvH3vLRDD8WsS6nLP5Ej8N3KbL0b7+VBA2AEZtwI03xdpdozoTnVoTCuIM5qbEz3sJqDn90DxkC76F/lx6+LNaqg4uIRSG08Q516ekNNpGZKCPxzjUd3gL1DuHplhEGFWGpTPTnT/LXvC69v2jJwGvTW54XWz20G0e0TCyqwTPsgumX4OV2luuEdPzIx8ZCMqC55YY8PR3If7mMA8hqjyzzN8Zlf/YxQ1jUoyIutvz9Hu004pAc9KOeTLMWV3V2D7tmZlfArb8mqTmxj9+kGs3xHFBrV0b7jZIg7esUM00x5+y63HodiennwtIXTy7sIZ+8tXqCqK4HC1q07tC1yixLMxke/Q9SPxaa8f62Y/Yojz2vEgYFuTXX4yJw7xyZETuxw5F1dal+ECblqL6raedppsZAQdXxh8zksw7ZXa7QXXTWd9Lvs7zuQ6G7ehcxXSk3eRulZ02y+Tzq4HTH0UheLXD+Ow7YkRNF2ciB784GIy5mylPlMECypqNP4l25PG/hvWEaL29mnIOmJTNH1A2mCazIE1IbkusPfw5AELo8LGDxaK2aFB2WXpe10gidgDjhVkh6FBIxwm6HLWzClF12SXwSQcil7Kmy8aVhUjkN6WWm80xgF8YFAN8XgblWPlRe1ethW+5WmOgDyTJ/Dm3pfFkav26M=
  template:
    metadata:
      name: homepage-homeassistant-token
      namespace: homepage
