---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA/PQ2bZAz1tZzNTdAT9ySBxPGjNLNv1V9rwxe9sJcGjWmt4fDZQbKq6o0PZn5EhB9SkGNbrzKrX8mx3oZLvfA5rg9lyinUuI9mQUJrviNFPu3fxlv++OdMr3KVKUoDTt2nTnvq9LM8b6gFw4CZokXHhuHLVCDJBMEEn2LTp7PkpByCb4hCwgoLZhWnUj/zJQ0AqP8ox4n5HGpITE6ozclkkHdSgVIxfCUeG9gINpGA9hXilH1UNZ/mUMIW2MSr7cq7u6iLs/WeduUfxKvZf44XTQlZShH4TMumpWFBdHtskIutaG+MZHdt5miQ+m/sw5o1Lx272UvG0TsnPYPJk2Zu4Ll1lGQmzNnchPLYQU1yTjdTNLAHTfXJ+pBzQ3fiqGGwPuaYiSUjw3J7JPFBSNiZZk8MJpRlzeCr+IKG18Ly/M1QpOzfLGQf2zr6S2a1ly7cjb199jD8HsmZ5snxlaACW71A9NVp0/7O4MrqH2ZMQeKan0fUtie34sNlUJlsdeS1/VGr6g0fRsuVMMvGiIBNx5bKJFPu3RM7a+QJyfA+7S3QT6TQKZcuvl1rJujJWrCw98O10wcvHeNEHaVbVXzFAkWd/meSpQl//eH19vqz2O7RXu3pHui28pb+7SUnJgGxOG3Cewk9pTReE2QNAPFlVxevwAh9jHd/lrzxtH3Ch7LZJxKdgTTE34Q0Se3mJesdHLBae78farF3zxEcV8aLgXYEWA==
    admin-user: AgCZN6D417kx6D/1xy7APKMDphAQwv6t6a1sNLrGwvrpevFN6d78CZGW220tcWIk7kUJ19k+fbo/XvPWdefth8PRid7gAZir2F+k2apJS0rQ8DYW0f4hMVyTj74cwftk+kXACO/j4prMU+9slGgea4QnAk8PAtIaMTc8CUFmqP8WGjF8Mpsk5ZrdEm4PT4YwPFhuR1T8fFkN7UGeuZdb9SVrgo3XUBkBMvGKnfCdrv0mv3ZiFZRsOz+DDIT2pSChHwxfNEsabwm+HsvrAp7T7jV82Es2qoSOjL5ViHTS9JNjMwjwH4p9+hzG2p/KSxqfQSUQWGMC8UNAh9t+A8EYyqqPIpqYcCKpY13hbljyDeq02CsnUpxlgjLIVtTtAmiHP9xK+g2KH8zkQZV1xhfrVjs/6seLUUAa8pIA3o8nVSLBZVzsWkj68kecH3Xzijjs/PnQ91f0sy0Krd7v7UUv3cODUTDknTY16MqzxmkBFyFd9lLqU3AnlDXawGXXT7WrThlS+SznAuOFl4cO2Fir+WUBIyjGU8z82GfqnRpnyuxcRsmw+Znak4W1qVA6KQpzmqvRnidTd9WbKVTnNBfX0mwjjceQhHyn37q/98L0jh/O+PEXKZGLzwIs0KJOxSOCB3qiNlchTHfUlgKYPg+2I2HBXqQNv3252Vtc5r7PKSzoE4HEOF2GWlujQauu4LbyYzCjSv25hg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
