---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root-credentials
  namespace: monitoring
spec:
  encryptedData:
    rootPassword: AgBYlMI92yRLGbSTfj38hcTjWEcZRAx6dXDwtFOmpOKLnaay1gDVNeoptxuG6cdHFM4NZLL4zLVS7QI1gGv7e1jDM1vKy4uTJxTOhNOZ54TeVU9zk9VKBN+RfaQJJOhsRV2OOPin9sSuYVpV4fYEscaPGZTtvbTi34Dmd+gx9TjXgUHfDzfGw+kfhJknBktvc8PBmp9nbMvLz3YtJoADixdhgwSqFJKuZSM0hT05aFhVW5hfwm40I4plzTVi2mGAAOJ2RTbCSnI6zmw68H1sxMF1dYEmO19yS99nX1f83JS4hLxhlsMfknVL/9MAGQPDumD7GK0lfZpcyJCiUXKyUzQNEM7XKHnAeYgbC4IFulks79i8vzRJ+8fgMo7GKJrmak2PsQmWC9gsKa433qQfh/fiwOb0a8wIow/J9q2JW7ZlYnn98FUOjal/ESz9AHn4Fs+O5vEV4ZgivnVWQgI714iHq+aEPtKQenUVqqPHR0WhuhNjaemkowqTzf93KkpQGIWLnHj3BtRr8qLEQn9JqcVaHjTvtQ0YBDLOG3Q43I+2VbvwCVGaqBJFGvDWH8qGy/HY9Hl79pMQfBxwiXhtLOZmT6LtHeEcaQtMTrvpMTrjEnDtdS7bJB2ifhlKv4KmReaLGO49ZJm1JuEyeQjaFMD7hqiXMx/oDjgRSQqDqehqVIX/FUI84Yc/4wQYRRkShUBDhNY0ELj/dNkvMrgPHabHRsy21ykgFlTMQWIyRQC3PA==
    rootUser: AgCGCr3Xiz+Z8HX79CzgU6LM+K3pWYx8v8gS8G/gZEj8NKptODKkx3PQkDew3mgtZaDnnwbXnXd47ANqub4xd7d1reTPYODfbs0CmnVDM9zOCs8L6UkuLyNer6DEVVf6sPAeDJzveSvm2uBB0ZwqSsTPVNjBhLaOANTWZodzi+lUTeX5VgB28iCUEy9vmPDx6JJlv7hDwR0DgrhhSQzoXcy5znpdRMMJ9ifBYB4mkExisRrNxgNcpXX7B2lkBHOnqx8p4q+mMK2T+JOTfhyWaGKRWj3YGJWkB8KdTEPI551DAnznXcHjwRKermJhEMlaSQjff44s/tcRSNL7R44L/apMAJ55qUrbqzOPgZmfOkSF0NTeqXnJlVrCnaVWdoTvQ0p9b3E3AO+/L7GvAgrQEIfqKeINNmbQEhQPbvSQ4TI3grRldIRhplKUUWXESdL0C92CUsAcuT+rNenvFfSOKTYM/AlcEN1JWNWrJiSsHunfvENJkvZ1yrm0XU3M92KQCAQTGV1MOmntx/xHdE6lo5R/QiZ7paBLHY77pP3gYGYAes1DX5c4v/89ku6G7APrTyw/j77BkFV4GFbKROLxQ8LSxA2Q/BTjz+8INQ888v9iZP44dKzuzeKXaqxElfVhS2LcZw7tGtVCUXv2aB5UMLWUU4hG07S1K5l5TohvmGSaAKl+UHRSr5F3m8vnndj+I0S8eEKW98LBhdcBWYurKVpsp6QUZStNb7q/AQqr9D2oyg==
  template:
    metadata:
      name: minio-root-credentials
      namespace: monitoring
