apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-external
  namespace: dns
data:
  Corefile: |
    bifrost22.dev:53 {
        errors
        forward . 10.43.0.10
        cache 30
        log
    }
    .:53 {
        errors
        forward . 1.1.1.1 1.0.0.1
        cache 30
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-external
  namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns-external
  template:
    metadata:
      labels:
        app: coredns-external
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: coredns
          image: coredns/coredns:1.11.3
          args:
            - -conf
            - /etc/coredns/Corefile
          ports:
            - containerPort: 53
              protocol: UDP
              hostPort: 53
            - containerPort: 53
              protocol: TCP
              hostPort: 53
          volumeMounts:
            - name: config
              mountPath: /etc/coredns
      volumes:
        - name: config
          configMap:
            name: coredns-external
