apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  bifrost22.server: |
    bifrost22.dev:53 {
        errors
        hosts {
            100.75.30.28 homepage.bifrost22.dev
            fallthrough
        }
        cache 30
    }
