apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool
spec:
  blocks:
    - cidr: 192.168.0.120/32
    - cidr: 100.75.30.28/32
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab-l2-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
    - ^eth[0-9]+
    - ^enp[0-9]+
    - ^tailscale[0-9]+
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: asgard
